### ISSUE TITLE
fix:  Failed to create directory (os error 45)

### ISSUE THREAD

**Issue by security-yunjae** [SkuldNorniern/fluere#74]
### Details

OS: macOS Sonoma 14.1 
Arch: Intel

Failed to create directory at config location with os error 45
```
sudo ./fluere online -i en0
Password:
Online mode
Interface en0 selected
path_file: "/home/<User>/.config/fluere/fluere.toml"
Failed to create directory at "/home/<User>/.config/fluere": Operation not supported (os error 45)
Requested Device : en0
-en0 device has been captured! in 3.757678ms
Created directory: ./output
```

<details open>
<summary>Checklist</summary>

- [X] Modify `fluere-config/src/init.rs` ✓ https://github.com/SkuldNorniern/fluere/commit/534f9142e5c2bd829755c38fa3ba9e1a33873657

![Flowchart](http://24.199.78.105:8082/public/9615e5e0c59ce822b72d5c4b92c41a72ccb5329ff6da5b41fc11920578c1ce49_74_flowchart.svg)
</details>

**Comment by SkuldNorniern** [comment]
the part, that you trying to fix it is not relevant to the error, change the part that actually tries to create the config file when is not there
